const CustomerRiskRatingConfigurationLocators = {
  modulePath: "/configuration/customer-risk-categorisation",
  configurationMenuLabel: "Configuration",
  customerRiskRatingMenuLabel: /Customer Risk Rating/i,

  tabCategoryWeights: "Category Weights & Parameters",
  tabRiskScoring: "Risk Scoring Configuration",
  tabPeriodicReview: "Periodic Review Frequency",

  panelCategoryWeights: "Category Weights & Parameters",
  panelRiskScoring: "Risk Scoring Configuration",
  panelPeriodicReview: "Periodic Review Frequency",

  breadcrumbText: "Customer Risk Rating Configuration",
  weightBannerText: /Total Category Weight \(must equal 100%\)/i,
  balancedStatusText: /Current:\s*\d+%.*Balanced/i,
  aboveWeightStatusText: /Current:\s*\d+%.*Above 100%/i,
  belowWeightStatusText: /Current:\s*\d+%.*Below 100%/i,
  categoryWeightInput: 'input[type="number"]',
  scoreChip: ".crr-score-chip",
  parameterRow: ".crr-factor-table tbody tr:not(.crr-section-row)",
  sectionRow: ".crr-section-row",
  parameterGridHeaders: [
    "Enabled",
    "Risk parameter",
    "Risk tier",
    "Score",
    "Override",
    "ONB",
    "ONG",
    "EVT",
    "PRD",
  ],
  riskTierLabels: [
    "Low",
    "Low-Medium",
    "Medium",
    "Medium-High",
    "High",
    "Critical",
  ],
  overrideLabels: ["No", "Override to High", "Override to Critical"],
  riskTierDefaultScores: {
    Critical: "100",
    High: "75",
    "Medium-High": "60",
    Medium: "40",
    "Low-Medium": "25",
    Low: "10",
  },
  categoryWeightTotalText: /All nine category weights must total exactly 100%/i,
  categoryDescriptionText:
    /Adjust category weightages, parameter risk levels, scores, override settings, and lifecycle stage applicability/i,

  categoryWeightsHeading:
    "Category Weights, Parameters & Stage Applicability",

  category4_1: /4\.1 Sanctions & Watchlist Risk/i,
  category4_2: /4\.2 Geographic & Jurisdictional Risk/i,
  category4_3: /4\.3 Transactional Behaviour Risk/i,
  category4_4: /4\.4 Business & Occupation Risk/i,
  category4_5: /4\.5 Customer Profile & KYC Risk/i,
  category4_6: /4\.6 Product & Service Risk/i,
  category4_7: /4\.7 Channel & Delivery Risk/i,
  category4_8: /4\.8 Financial Profile Risk/i,
  category4_9: /4\.9 Entity Type & Corporate Structure/i,

  stageONB: ".crr-stage-pill--onb",
  stageONG: ".crr-stage-pill--ong",
  stageEVT: ".crr-stage-pill--evt",
  stagePRD: ".crr-stage-pill--prd",

  saveConfigurationButton: "Save Configuration",
  makerCheckerHeading: "Maker-checker requests",
  auditHistoryHeading: "Configuration audit history",
  filterAuditButton: "Filter audit",
  pendingButton: "Pending",
  allRequestsButton: "All requests",
  refreshButton: "Refresh",
  noRequestsMessageText: /No maker-checker requests were returned/i,
  pendingApprovalText: /pending approval|awaiting checker|submitted for approval|pending review/i,
  approveRequestButton: /^Approve$/i,
  rejectRequestButton: /^Reject$/i,
  makerCheckerRequestRow: ".crr-mc-request-row, [data-testid='crr-mc-request-row']",

  configurationTable: "table.crr-factor-table",
  sanctionsRegionHeading: /4\.1\s*Sanctions.*Watchlist Risk/i,

  riskClassificationHeading: "Risk Classification by Composite Score",
  parameterScoreMappingHeading: "Parameter Risk Tier → Numeric Score Mapping",
  saveScoringConfigButton: /Save Scoring Config/i,
  compositeScoreInput: 'input[type="number"]',

  periodicReviewHeading: "Periodic Review Frequency Configuration",
  saveReviewScheduleButton: /Save Review Schedule/i,
  periodicTierCritical: "■ Critical Risk",
  periodicTierHigh: "■ High Risk",
  periodicTierMedium: "■ Medium Risk",
  periodicTierLow: "■ Low Risk",
  periodicReviewFrequencyLabel: /Review Frequency \(months\)/i,
  periodicMinMonthsLabel: /Min \(months\)/i,
  periodicMaxMonthsLabel: /Max \(months\)/i,

  parameterOfacSdn: /OFAC SDN \/ EU & UK HMT Sanctions/i,
  parameterUnSecurityCouncil: /UN Security Council \/ Taliban Sanctions/i,
  parameterInternalBankBlacklist: /Internal Bank Blacklist/i,
};

export default CustomerRiskRatingConfigurationLocators;
