const CustomerRiskRatingConfigurationLocators = {
  modulePath: "/configuration/customer-risk-categorisation",
  tabCategoryWeights: "Category Weights & Parameters",
  tabRiskScoring: "Risk Scoring Configuration",
  tabPeriodicReview: "Periodic Review Frequency",
  weightBannerText: /Total Category Weight \(must equal 100%\)/i,
  balancedBannerText: /Current:\s*100%\s*—\s*Balanced/i,
  saveConfigurationButton: "Save Configuration",
  saveScoringConfigButton: "Save Scoring Config",
  saveReviewScheduleButton: "Save Review Schedule",
  riskClassificationHeading: "Risk Classification by Composite Score",
  parameterScoreMappingHeading: "Parameter Risk Tier → Numeric Score Mapping",
  periodicReviewHeading: /Periodic Review Frequency Configuration/i,
  makerCheckerSection: /Maker-checker requests/i,
  pendingApprovalText: /pending approval|awaiting checker|submitted for approval|pending review/i,
  categorySidebarItem: /^4\.\d/,
  parameterOfacSdn: /OFAC SDN \/ EU & UK HMT Sanctions/i,
  overrideLabels: ["No", "Override to High", "Override to Critical"],
  riskTierLabels: [
    "Low",
    "Low-Medium",
    "Medium",
    "Medium-High",
    "High",
    "Critical",
  ],
  compositeTierLabels: ["LOW RISK", "MEDIUM RISK", "HIGH RISK", "CRITICAL RISK"],
  periodicTierCritical: /CRITICAL RISK/i,
  periodicTierHigh: /HIGH RISK/i,
  periodicTierMedium: /MEDIUM RISK/i,
  periodicTierLow: /LOW RISK/i,
  categoryNames: [
    "Sanctions & Watchlist Risk",
    "Geographic & Jurisdictional Risk",
    "Transactional Behaviour Risk",
    "Business & Occupation Risk",
    "Customer Profile & KYC Risk",
    "Product & Service Risk",
    "Channel & Delivery Risk",
    "Financial Profile Risk",
    "Entity Type & Corporate Structure",
  ],
  overrideValueByLabel: {
    No: "NO",
    "Override to High": "OVERRIDE_TO_HIGH",
    "Override to Critical": "OVERRIDE_TO_CRITICAL",
  } as Record<string, string>,
};

export default CustomerRiskRatingConfigurationLocators;
