const DedupScreeningLocators = {
  dedupScreeningLink: 'a[href*="dedup-screening"]',
  pageTitle: ".ds-page-title, .ds-topbar-title",
  pageSubtitle: ".ds-page-subtitle",
  breadcrumb: ".ds-breadcrumb",
  filterCard: ".ds-filter-card",
  matchParameterTrigger: ".ds-multiselect-trigger, button[aria-label='Match Parameter List']",
  matchParameterPanel: "[data-radix-popper-content-wrapper], [role='listbox']",
  matchParameterSearch: 'input[aria-label="Search parameters..."], input[placeholder*="Search parameters" i]',
  parameterTag: ".ds-multiselect-tags .ds-tag, .ds-tag",
  parameterTagRemove: ".ds-tag-remove",
  customerIdInput: ".ds-form-input[placeholder*='Customer ID' i], input[placeholder*='Customer ID' i]",
  generateReportButton: "button.ds-btn-primary:has-text('Generate Report'), button:has-text('Generate Report')",
  clearFiltersButton: "button.ds-btn-ghost:has-text('Clear Filters'), button:has-text('Clear Filters')",
  resultsSection: ".ds-results-section",
  resultsReportTitle: ".ds-results-title",
  resultsStatusBar: ".ds-status-bar",
  resultsTableWrap: ".ds-table-wrap",
  resultsTable: "table.ds-table, .ds-table-wrap table",
  resultsTableRow: "table.ds-table tbody tr, .ds-table-wrap table tbody tr",
  compareModal: ".ds-modal-overlay.open, .ds-compare-modal, [role='dialog']",
  compareButton: "button.ds-view-btn, button[aria-label*='Compare' i]",
  exportWrapper: ".ds-export-wrapper",
  exportPanel: "[role='menu'], .ds-export-panel",
  exportOption: "[role='menuitem'], .ds-export-option",
  exportReportButton: ".ds-export-wrapper button:has-text('Export'), .ds-results-section button:has-text('Export')",
  pagination: ".ds-pagination",
  paginationNext: ".ds-pagination button[aria-label='Next page'], button[aria-label='Next page']",
  paginationPrev: ".ds-pagination button[aria-label='Previous page'], button[aria-label='Previous page']",
  emptyState: "text=/no duplicate|no records|no results|no matching/i",
  validationMessage: "[role='alert'], .text-destructive, .text-red-500, input.ds-form-input[aria-invalid='true']",
};

export default DedupScreeningLocators;
