const KeywordManagerLocators = {
  pageTitle: "h1:has-text('Keyword Manager'), h1:has-text('Keyword Configuration'), h1:has-text('Screening – Keyword Configuration'), h1:has-text('Screening - Keyword Configuration'), [class*='keyword-manager'] h1",
  pageSubtitle: ".keyword-manager-subtitle, [class*='subtitle']",
  configurationMenu: "button:has-text('Configuration'), button:has-text('Configurations'), [aria-label*='Configuration']",
  configurationSubmenu: "[class*='configuration-submenu'], nav:has-text('Configuration')",
  keywordManagerLink: "nav a[href*='configuration/keyword-manager'], aside a[href*='configuration/keyword-manager'], [class*='sidebar'] a[href*='configuration/keyword-manager'], a[href='/configuration/keyword-manager']",
  keywordManagerSidebarLabel: "Screening – Keyword Configuration, Screening - Keyword Configuration, Keyword Configuration, Keyword Manager",
  toolbar: "[class*='toolbar'], [class*='action-bar'], header[class*='toolbar']",
  searchInput: "input[placeholder*='Search keyword'], input[placeholder*='phrase'], input[placeholder*='Search'], input[type='search']",
  searchClearButton: "button[aria-label*='Clear'], button:has-text('Clear')",
  tabList: "[role='tablist'], .keyword-manager-tabs, nav[class*='tabs']",
  tabPanel: "[role='tabpanel'], .tab-panel, [class*='tab-content']",
  activeTab: "[role='tab'][aria-selected='true']",
  dataTable: "table, [role='grid'], [class*='data-table'], [class*='keyword-table']",
  tableHeader: "table thead th, [role='columnheader']",
  tableRow: "table tbody tr, [role='row']",
  categoryBadge: "[class*='category-badge'], [class*='badge'][class*='category'], span[class*='pill']",
  statusBadge: "[class*='status-badge'], [data-testid='status-badge']",
  screeningFieldBadge: "[class*='screening-field'], [class*='field-badge'], [data-testid='screening-field']",
  rowActionButton: "button[aria-label*='action'], button:has-text('Disable'), button:has-text('Enable'), [class*='row-action']",
  rowActionsMenu: "button[aria-label*='More'], button[aria-label*='Actions'], [class*='kebab']",
  exportButton: "button:has-text('Export')",
  addCategoryButton: "button:has-text('Add Category')",
  categoryControlsButton: "button:has-text('Category Controls'), button[aria-label*='Category Controls']",
  addKeywordButton: "button:has-text('Add Keyword')",
  bulkImportButton: "button:has-text('Bulk Import'), button:has-text('Import'), button:has-text('Upload')",
  liveNarrativeTester: "[class*='narrative-tester'], [class*='live-narrative'], [data-testid='narrative-tester']",
  makerCheckerQueue: "[class*='maker-checker'], [class*='approval-queue'], button:has-text('Approval Queue')",
  addCategoryModal: "#modal-add-category, [role='dialog'][aria-label='Add Category'], [class*='add-category-modal']:not(.km-hidden)",
  categoryControlsModal: "#modal-category-controls, [role='dialog'][aria-label='Category Controls'], [class*='category-controls']:not(.km-hidden)",
  addKeywordPanel: "#modal-add-keyword, aside.add-keyword[aria-label='Add Keyword'], [role='dialog'][aria-label='Add Keyword']",
  bulkImportModal: "#modal-bulk-import, [role='dialog'][aria-label='Bulk Import'], [class*='bulk-import']:not(.km-hidden)",
  disableConfirmModal: "#modal-disable-confirm, [role='dialog'][aria-label='Confirm Disable'], [class*='disable-confirm']:not(.km-hidden)",
  categoryNameInput: "input[name*='category'], input[placeholder*='Category name'], [data-testid='category-name']",
  keywordPhraseInput: "input[name*='keyword'], input[placeholder*='keyword'], textarea[placeholder*='keyword'], textarea[placeholder*='phrase']",
  categorySelect: "select[name*='category'], [data-testid='category-select']",
  screeningFieldsSelect: "select[name*='screening'], [data-testid='screening-fields'], [class*='screening-fields']",
  narrativeTextarea: "textarea[placeholder*='narrative'], textarea[name*='narrative'], [data-testid='narrative-input']",
  modalOverlay: "[class*='overlay'], [class*='backdrop']",
  modalSubmitButton: "button:has-text('Submit'), button:has-text('Create'), button:has-text('Add'):not(:has-text('Add Category')):not(:has-text('Add Keyword'))",
  modalCancelButton: "button:has-text('Cancel'), button:has-text('Close')",
  modalApproveButton: "button:has-text('Approve'), button:has-text('Confirm')",
  modalRejectButton: "button:has-text('Reject'), button:has-text('Decline')",
  modalConfirmButton: "button:has-text('Confirm'), button:has-text('Yes'), button:has-text('Disable')",
  retryButton: "button:has-text('Retry'), button:has-text('Try Again')",
  loadingIndicator: "[class*='loading'], [class*='skeleton'], [class*='spinner'], [aria-busy='true']",
  emptyState: ".empty-state, [class*='empty-state'], [class*='no-data'], [class*='no-results']",
  errorState: "[class*='error-state'], [role='alert'], [class*='error-message']",
  validationError: "[class*='validation-error'], [class*='field-error'], .error-text",
  duplicateError: "[class*='duplicate'], text=/duplicate/i",
  toastNotification: "[class*='toast'], [role='status'][class*='toast'], .notification-toast",
  paginationNext: "button[aria-label='Next page'], button:has-text('Next')",
  bulkImportFileInput: "input[type='file']",
  bulkImportTemplateLink: "a:has-text('template'), button:has-text('Download template')",
  narrativeHighlight: "[class*='highlight'], mark, [class*='match-highlight']",
};

export default KeywordManagerLocators;
