const BatchScreeningLocators = {
  batchScreeningLink: "a[href='/screening/batch-screening'], a.sidebar-link[href*='batch-screening']",
  sanctionsScreeningLink: "a[href*='screening'], a:has-text('Sanctions Screening')",
  matchResultsHeading: "h1",
  matchResultsTotalBadge: "text=/\\d+\\s+Total/i",
  moduleTabMatchResults: "button[role='tab']:has-text('Match Results'), [role='tab']:has-text('Match Results')",
  batchControlsTablist: "[role='tablist'][aria-label*='Batch screening'], [role='tablist']",
  startBatchTab: "[role='tab']:has-text('Start Batch')",
  scheduleBatchTab: "[role='tab']:has-text('Schedule Batch')",
  manualStopTab: "[role='tab']:has-text('Manual Stop')",
  runBatchNowButton: "button:has-text('Run Batch Now')",
  saveScheduleButton: "button:has-text('Save Schedule')",
  watchlistRuleSelect: "select, [role='combobox']",
  exportReportButton: "button:has-text('Export Report')",
  clearFiltersButton: "button:has-text('Clear Filters'), button:has-text('× Clear Filters')",
  periodDropdown: "button:has-text('This Year'), button:has-text('Period')",
  searchInput: "input[type='search'], [role='searchbox'], input[placeholder*='Search by name']",
  resultsTable: "table",
  resultsTableRow: "table tbody tr",
  paginationNext: "button[aria-label='Next page'], button:has-text('Next')",
  paginationPrev: "button[aria-label='Previous page'], button:has-text('Previous')",
  screeningResultsHeading: "h1:has-text('Screening Results')",
  matchReviewHeading: "text=Match Review",
  aiSummaryTab: "[role='tab']:has-text('AI Summary')",
  matchDetailsTab: "[role='tab']:has-text('Match Details')",
  viewSummaryTab: "[role='tab']:has-text('View Summary')",
  falsePositiveButton: "button:has-text('False Positive')",
  confirmMatchButton: "button:has-text('Confirm Match')",
  reportButton: "button:has-text('Report')",
  commentDialog: "[role='dialog']",
  commentInput: "[role='dialog'] textarea, [role='dialog'] input[type='text']",
  dialogConfirmButton: "[role='dialog'] button:has-text('Confirm')",
  dialogCancelButton: "[role='dialog'] button:has-text('Cancel')",
  underReviewButton: "button:has-text('Under Review')",
  viewFullProfileButton: "button:has-text('View Full Profile')",
  escalateCaseButton: "button:has-text('Escalate Case')",
  emptyState: ".empty-state, [class*='empty-state'], [class*='EmptyState']",
  unauthorizedMessage: "text=/access denied|unauthorized|not authorized|login required/i",
  loadingIndicator: "text=Loading module content",
};

export default BatchScreeningLocators;
