const BatchScreeningLocators = {
  batchScreeningLink: "a[href='/screening/batch-screening'], a.sidebar-link[href*='batch-screening']",
  sanctionsScreeningLink: "a[href*='screening'], a:has-text('Sanctions Screening')",
  matchResultsHeading: "h1",
  matchResultsTotalBadge: "text=/\\d+\\s+Total/i",
  moduleTabMatchResults: "button[role='tab']:has-text('Match Results'), [role='tab']:has-text('Match Results')",
  batchControlsTablist: "[role='tablist'][aria-label*='Batch screening'], [role='tablist']",
  startBatchTab: "[role='tab']:has-text('Start Batch')",
  scheduleBatchTab: "[role='tab']:has-text('Schedule Batch')",
  manualStopTab: "[role='tab']:has-text('Manual Stop')",
  runBatchNowButton: "button:has-text('Run Batch Now')",
  saveScheduleButton: "button:has-text('Save Schedule')",
  watchlistRuleSelect: "select, [role='combobox']",
  exportReportButton: "button:has-text('Export Report')",
  dateDropdownBtn: "#date-dd-btn, .date-dropdown-btn",
  filterChip: ".filter-chip",
  filterChipDateRange: "#fc-date",
  filterChipBranch: "#fc-branch",
  filterChipCustomerId: "#fc-custid",
  filterChipAccountNo: "#fc-acct",
  filterChipScreeningType: "#fc-scrtype",
  filterChipListName: "#fc-listname",
  filterPanelApply: ".filter-panel-apply, button:has-text('Apply')",
  topNavTab: ".lp-tab, button.lp-tab",
  clearFiltersButton: "button:has-text('Clear Filters'), button:has-text('× Clear Filters')",
  periodDropdown: "button:has-text('This Year'), button:has-text('Period')",
  searchInput: "input[type='search'], [role='searchbox'], input[placeholder*='Search by name']",
  resultsTable: "table",
  resultsTableRow: "table tbody tr",
  matchedCountLink: "button.matched-count-link, .matched-count-link",
  paginationNext: "button[aria-label='Next page'], button:has-text('Next')",
  paginationPrev: "button[aria-label='Previous page'], button:has-text('Previous')",
  screeningResultsHeading: "h1:has-text('Screening Results')",
  matchReviewHeading: "text=Match Review",
  aiSummaryTab: "[role='tab']:has-text('AI Summary')",
  matchDetailsTab: "[role='tab']:has-text('Match Details')",
  viewSummaryTab: "[role='tab']:has-text('View Summary')",
  falsePositiveButton: "button:has-text('False Positive')",
  confirmMatchButton: "button:has-text('Confirm Match')",
  reportButton: "button:has-text('Report')",
  commentDialog: "#comment-modal, .modal-overlay#comment-modal, .modal-overlay, [role='dialog']",
  commentInput: "#modal-comment, .modal-textarea, textarea[placeholder*='comment' i], [role='dialog'] textarea, [role='dialog'] input[type='text']",
  dialogConfirmButton: "#comment-modal button:has-text('Confirm'), .modal-overlay button:has-text('Confirm Action'), .modal-overlay button:has-text('Confirm'), [role='dialog'] button:has-text('Confirm')",
  dialogCancelButton: "#comment-modal button:has-text('Cancel'), .modal-overlay button:has-text('Cancel'), [role='dialog'] button:has-text('Cancel')",
  underReviewButton: "button:has-text('Under Review')",
  actionDropdownBtn: ".action-dropdown-btn",
  actionDropdownMenu: ".action-dropdown-menu",
  actionDropdownItem: ".action-dropdown-item",
  dispositionDropdownBtn: "button.action-dropdown-btn, td:last-child button[aria-haspopup], [class*='action-dropdown'] button",
  viewFullProfileButton: "button:has-text('View Full Profile')",
  escalateCaseButton: "button:has-text('Escalate Case')",
  emptyState: ".empty-state, [class*='empty-state'], [class*='EmptyState']",
  unauthorizedMessage: "text=/access denied|unauthorized|not authorized|login required/i",
  loadingIndicator: "text=Loading module content",
};

export default BatchScreeningLocators;
