const ExceptionListManagerLocators = {
  pageTitle: "h1:has-text('Exception List'), h1:has-text('Exception Lists'), h1:has-text('CSEL'), [class*='exception-list'] h1",
  pageSubtitle: ".exception-list-subtitle, [class*='subtitle']",
  configurationMenu: "button:has-text('Configuration'), button:has-text('Configurations'), [aria-label*='Configuration']",
  configurationSubmenu: "[class*='configuration-submenu'], nav:has-text('Configuration')",
  exceptionListLink: "a:has-text('Exception List'), a:has-text('Exception Lists'), a:has-text('CSEL'), a[href*='exception-lists']",
  summaryCards: "[class*='summary-card'], [class*='stat-card'], [class*='dashboard-card'], [data-testid='summary-cards']",
  summaryCardMetric: "[class*='summary-card'] [class*='metric'], [class*='stat-card'] [class*='value']",
  toolbar: "[class*='toolbar'], [class*='action-bar'], header[class*='toolbar']",
  searchInput: "input[placeholder*='Search list'], input[placeholder*='Search exception'], input[placeholder*='Search'], input[type='search']",
  searchClearButton: "button[aria-label*='Clear'], button:has-text('Clear')",
  categoryFilter: "select[name*='category'], [data-testid='category-filter'], [class*='category-filter']",
  scopeFilter: "select[name*='scope'], [data-testid='scope-filter'], [class*='scope-filter'], select[name*='jurisdiction']",
  listGrid: "table, [role='grid'], [class*='data-table'], [class*='exception-list-table'], [class*='list-grid']",
  tableHeader: "table thead th, [role='columnheader']",
  tableRow: "table tbody tr, [role='row']",
  categoryBadge: "[class*='category-badge'], [class*='badge'][class*='category'], span[class*='pill']",
  scopeBadge: "[class*='scope-badge'], [class*='jurisdiction-badge'], [data-testid='scope-badge']",
  statusBadge: "[class*='status-badge'], [data-testid='status-badge']",
  rowActionButton: "button[aria-label*='action'], button:has-text('Suspend'), button:has-text('Delete'), [class*='row-action']",
  rowActionsMenu: "button[aria-label*='More'], button[aria-label*='Actions'], [class*='kebab']",
  exportButton: "button:has-text('Export')",
  createListButton: "button:has-text('Create List'), button:has-text('New List'), button:has-text('Add List')",
  addEntryButton: "button:has-text('Add Entry'), button:has-text('New Entry'), button:has-text('Add Exception Entry')",
  bulkUploadButton: "button:has-text('Bulk Upload'), button:has-text('Import'), button:has-text('Upload')",
  auditTrailButton: "button:has-text('Audit Trail'), button:has-text('Audit History'), button[aria-label*='Audit']",
  makerCheckerQueue: "[class*='maker-checker'], [class*='approval-queue'], button:has-text('Approval Queue'), button:has-text('Maker-Checker')",
  registerReportLink: "a:has-text('Exception Register'), a:has-text('Register Report'), button:has-text('Register Report'), a[href*='register-report']",
  registerReportSection: "[class*='register-report'], [class*='exception-register'], [data-testid='register-report']",
  reportFilterPanel: "[class*='report-filter'], [class*='filter-panel'], form[class*='report-filters']",
  reportSection: "[class*='report-section'], section[class*='report'], [data-testid*='report-section']",
  createListModal: "#modal-create-list, [role='dialog'].create-list-modal, [class*='create-list-modal']",
  listDetailView: "#elm-list-detail, [class*='list-detail'], [class*='exception-list-detail']",
  entryGrid: "#elm-list-detail [data-testid='entry-grid'], [class*='entry-grid'], [class*='entry-table'], [data-testid='entry-grid']",
  addEntryForm: "#modal-add-entry, [class*='add-entry']",
  bulkUploadModal: "#modal-bulk-upload, [role='dialog']:has-text('Bulk Upload'), [class*='bulk-upload']",
  auditTrailPanel: "#modal-audit-trail, [class*='audit-trail'], [data-testid='audit-trail-panel']",
  makerCheckerModal: "#modal-maker-checker, [class*='maker-checker-modal']",
  suspendWarningModal: "#modal-suspend-warning",
  confirmDeleteModal: "#modal-delete-confirm, [class*='delete-confirm']",
  listNameInput: "input[name*='listName'], input[name*='name'], input[placeholder*='List name'], [data-testid='list-name']",
  listCategorySelect: "select[name*='category'], [data-testid='list-category-select'], [class*='list-category-select']",
  listScopeSelect: "select[name*='scope'], select[name*='jurisdiction'], [data-testid='list-scope-select'], [class*='list-scope-select']",
  listDescriptionInput: "textarea[name*='description'], input[placeholder*='Description'], [data-testid='list-description']",
  reviewFrequencyInput: "input[name*='review'], input[name*='frequency'], [data-testid='review-frequency']",
  customerIdInput: "input[name*='customer'], input[placeholder*='Customer ID'], [data-testid='customer-id']",
  reasonCodeSelect: "select[name*='reason'], [data-testid='reason-code-select'], [class*='reason-code-select']",
  evidenceReferenceInput: "input[name*='evidence'], input[placeholder*='Evidence'], textarea[name*='evidence'], [data-testid='evidence-reference']",
  expiryDateInput: "input[name*='expiry'], input[type='date'], input[placeholder*='Expiry'], [data-testid='expiry-date']",
  entryCommentsInput: "textarea[name*='comment'], textarea[placeholder*='Comment'], input[placeholder*='Comment'], [data-testid='entry-comments']",
  approvalCommentInput: "textarea[name*='comment'], input[placeholder*='comment'], input[placeholder*='reason'], [data-testid='approval-comment']",
  evaluationTester: "[class*='evaluation-tester'], [class*='match-tester'], [data-testid='evaluation-tester']",
  evaluationInput: "textarea[placeholder*='evaluate'], input[placeholder*='test name'], [data-testid='evaluation-input']",
  matchResultHighlight: "[class*='match-result'], [class*='highlight'], mark, [class*='fuzzy-match']",
  multilingualMatchResult: "[class*='multilingual'], [class*='native-script'], [data-testid='multilingual-match']",
  confirmationBanner: "[class*='confirmation'], [class*='success-banner'], [role='alert'][class*='success'], [class*='toast'][class*='success']",
  modalOverlay: "[class*='overlay'], [class*='backdrop']",
  panelOverlay: "[class*='panel-overlay'], [class*='drawer-overlay']",
  backArrow: "button[aria-label*='Back'], button[class*='back'], [class*='back-arrow']",
  breadcrumbNav: "nav[aria-label*='breadcrumb'], [class*='breadcrumb']",
  modalSubmitButton: "button:has-text('Submit'), button:has-text('Save'), button:has-text('Create'), button:has-text('Add')",
  modalCancelButton: "button:has-text('Cancel'), button:has-text('Close')",
  modalApproveButton: "button:has-text('Approve'), button:has-text('Confirm')",
  modalRejectButton: "button:has-text('Reject'), button:has-text('Decline')",
  modalConfirmButton: "button:has-text('Confirm'), button:has-text('Yes'), button:has-text('Delete')",
  retryButton: "button:has-text('Retry'), button:has-text('Try Again')",
  loadingIndicator: "[class*='loading'], [class*='skeleton'], [class*='spinner'], [aria-busy='true']",
  emptyState: ".empty-state, [class*='empty-state'], [class*='no-data'], [class*='no-results']",
  errorState: "[class*='error-state'], [role='alert'], [class*='error-message']",
  validationError: "[class*='validation-error'], [class*='field-error'], .error-text",
  duplicateError: "[class*='duplicate'], text=/duplicate/i",
  toastNotification: "[class*='toast'], [role='status'][class*='toast'], .notification-toast",
  paginationNext: "button[aria-label='Next page'], button:has-text('Next')",
  bulkUploadFileInput: "input[type='file']",
  bulkUploadTemplateLink: "a:has-text('template'), button:has-text('Download template')",
  auditTimeline: "[class*='timeline'], [class*='audit-list'], [class*='history-list']",
  auditEventRow: "[class*='audit-event'], [class*='timeline-item'], li[class*='audit']",
  rbacRestrictedControl: "button:has-text('Create List'), button:has-text('Add Entry'), button:has-text('Delete')",
  sidebar: "[class*='sidebar'], nav[class*='sidebar'], aside[class*='sidebar']",
  sidebarActiveItem: "[class*='sidebar'] [aria-current='page'], [class*='sidebar'] [class*='active'], [class*='sidebar'] a[class*='selected']",
  mainContent: "main, [class*='main-content'], [class*='content-area']",
};

export default ExceptionListManagerLocators;
