const KycGapReportLocators = {
  gapReportTitle: "h1.gap-report-title",
  gapReportSubtitle: ".gap-report-subtitle, p.subtitle, [class*='subtitle']",
  kycModuleNav: "nav a:has-text('KYC'), [class*='sidebar'] button:has-text('KYC'), [class*='sidebar'] a:has-text('KYC')",
  kycGapReportLink: "a.sidebar-link[href='/kyc/kyc-gap-report'], a[href='/kyc/kyc-gap-report']:has-text('KYC Gap Report')",
  gapReportBreadcrumb: "nav[aria-label='breadcrumb'], .breadcrumb, [class*='breadcrumb']",
  exportButton: "button:has-text('Export')",
  clearFiltersButton: "button:has-text('Clear Filters')",
  refreshButton: "button:has-text('Refresh')",
  searchInput: "input[placeholder*='Search customer'], input[placeholder*='Search'], input[type='search']",
  branchFilter: ".gap-filters combobox:first-of-type",
  customerTypeFilter: ".gap-filters combobox:nth-of-type(2)",
  templateFilter: ".gap-filters combobox:nth-of-type(3)",
  priorityFilter: ".gap-filters combobox:nth-of-type(4)",
  scoreMinInput: "input.gap-score-input[placeholder='Min'], input.gap-score-input:first-of-type, input[name*='scoreMin']",
  scoreMaxInput: "input.gap-score-input[placeholder='Max'], input.gap-score-input:last-of-type, input[name*='scoreMax']",
  gapReportTable: "table",
  gapReportTableRow: "table tbody tr:not(:has(td.gap-table-empty))",
  gapReportColumnHeader: "table thead th",
  gapReportKpiCard: ".kpi-card, [class*='kpi-card'], .gap-kpi",
  kpiTotalCustomers: "[class*='kpi']:has-text('Total Customers'), .kpi-card:has-text('Total Customers')",
  kpiCustomersWithGaps: "[class*='kpi']:has-text('Customers with Gaps'), .kpi-card:has-text('Customers with Gaps')",
  kpiCriticalPriority: "[class*='kpi']:has-text('Critical'), .kpi-card:has-text('Critical Priority')",
  kpiHighPriority: "[class*='kpi']:has-text('High Priority'), .kpi-card:has-text('High Priority')",
  kpiMediumPriority: "[class*='kpi']:has-text('Medium Priority'), .kpi-card:has-text('Medium Priority')",
  kpiLowPriority: "[class*='kpi']:has-text('Low Priority'), .kpi-card:has-text('Low Priority')",
  gapReportPaginationNext: "button[aria-label='Next page'], button.gap-page-nav-btn:has-text('Next')",
  gapReportPaginationPrev: "button[aria-label='Previous page'], button.gap-page-nav-btn:has-text('Previous')",
  gapReportPageSizeSelect: "combobox:has(option[value='10']), select[name*='pageSize'], select.page-size",
  gapReportPageIndicator: ".pagination-info, [class*='page-indicator'], [class*='item-range'], text=/Page \\d+ of \\d+/",
  gapReportDetailModal: ".gap-detail-modal, .gap-detail-overlay.open .modal, [role='dialog'] .gap-detail-modal",
  gapReportMissingFieldsSection: ".missing-fields, [class*='missing-fields']",
  gapReportScoreBreakdown: ".score-breakdown, [class*='score-breakdown']",
  gapTypeBadge: ".gap-type-badge, [class*='gap-type'], [class*='badge']",
  gapReportEmptyState: "td.gap-table-empty, .empty-state, [class*='empty-state']",
  viewActionButton: "button.gap-view-btn, button[aria-label*='View gap details']",
  gapPriorityCell: "table tbody tr td[class*='priority'], table tbody tr td:nth-child(6)",
  gapScoreCell: "table tbody tr td:nth-child(7)",
};

export default KycGapReportLocators;
