const MissingMandatoryLocators = {
  missingMandatoryLink: "a.sidebar-link:has-text('Missing Mandatory Data')",
  listPanel: "main complementary:has-text('Templates'), aside.list-panel, main [class*='template-list']",
  templateItem: "main complementary button, button.template-item",
  createTemplateButton: "main button:has-text('Create Template')",
  createTemplateView: "main :text('Create New Template'), main :text('Template Name')",
  createTemplateNameInput: "input[placeholder*='Simplified KYC'], input[placeholder*='Template Name' i]",
  tabButton: "button.tab-btn, [role='tab'], main nav button",
  addFieldButton: "button:has-text('+ Add Field'), button:has-text('Add Field'), button:has-text('Add Custom Field')",
  saveChangesButton: "button:has-text('Save Changes')",
  dialog: "[role='dialog'], [class*='modal']:visible",
  templateSearchInput: "main input[placeholder*='Search' i], main input[type='search'], aside.list-panel input[type='search']",
  templateCountBadge: "main complementary .list-panel-count, aside.list-panel .list-panel-count",
  templateDetailHeader: ".template-detail-header, .template-info-meta, main h1, main h2",
  fieldRow: ".field-row, [class*='field-row'], table tbody tr, input[type='checkbox']",
  requirementDropdown: "[role='combobox'], select[name*='requirement'], [class*='requirement'] select",
  fieldCheckbox: "input[type='checkbox']",
  lockedFieldBadge: "[class*='locked'], .badge:has-text('Locked'), [data-locked='true'], :text('Locked')",
  cancelButton: "button:has-text('Cancel'), button:has-text('Back')",
  closeDialogButton: "[role='dialog'] button[aria-label='Close'], [role='dialog'] .modal-close, button:has-text('Cancel')",
  errorMessage: ".error-message, [class*='error'], [role='alert'], :text-matches('required|mandatory', 'i')",
  unauthorizedMessage: "text=/unauthorized|access denied|forbidden|sign in|log in|not authorized|permission denied/i",
  emptyState: ".empty-state, [class*='empty-state'], :text-matches('select a template|no templates|templates\\\\s+0', 'i')",
  kycGapReportLink: "a[href='/kyc/kyc-gap-report']",
  gapReportSearchInput: "input[placeholder*='Search customer'], input[placeholder*='Search'], input[type='search']",
  gapReportTable: "main main table, main table, [class*='gap-report'] table",
  gapReportEmptyState: ":text-matches('no (customers|records|data)', 'i'), [class*='empty-state']",
  appShell: "body",
  topBar: "header, .top-bar, [class*='top-bar']",
  sidebar: "nav, aside.sidebar, [class*='sidebar']",
  weightageDropdown: "[role='dialog'] select, [role='dialog'] [role='combobox'], [role='dialog'] [class*='weightage'] select",
  fieldNameInput: "[role='dialog'] input, input[placeholder*='Field Name' i], input[placeholder*='name' i]",
  sectionSelect: "[role='dialog'] select, [role='dialog'] [role='combobox'], select[name*='section']",
  descriptionInput: "[role='dialog'] textarea, [role='dialog'] input[name*='description'], textarea",
  scoreConfigTab: "button.tab-btn:has-text('KYC Gap Score'), [role='tab']:has-text('KYC Gap Score'), button:has-text('Gap Score')",
  scoreRangeInput: "[role='spinbutton'], input[type='number'], input[name*='range'], .score-range input",
  tipBar: "[class*='tip-bar'], [class*='guidance'], :text-matches('score|range|tip|guidance', 'i')",
  cloneButton: "button:has-text('Clone'), button:has-text('Clone Template'), [aria-label*='Clone' i]",
};

export default MissingMandatoryLocators;
