const ScreeningConfigurationLocators = {
  screeningConfigLink: 'a[href*="sanction-screening-config"]',
  configurationsMenu: 'text=/^Configurations$/i',
  pageBreadcrumb: 'nav[aria-label="Sanctions screening configuration breadcrumb"]',
  pageTitle: 'nav[aria-label="Sanctions screening configuration breadcrumb"], main :text-is("Sanctions Screening Configuration")',
  pageSubtitle: "text=/watchlist|screening configuration/i",
  statusTabList: 'tablist[aria-label="Watchlist status filters"]',
  activeTab: 'tablist[aria-label="Watchlist status filters"] [role="tab"]:has-text("Active")',
  inactiveTab: 'tablist[aria-label="Watchlist status filters"] [role="tab"]:has-text("Inactive")',
  allRulesTab: 'tablist[aria-label="Watchlist status filters"] [role="tab"]:has-text("All Rules")',
  searchBox: '[placeholder*="Search profiles" i], [role="searchbox"]',
  viewListsLibraryButton: 'button:has-text("View Lists Library")',
  uploadListButton: 'button:has-text("Upload List")',
  createWatchlistButton: 'button:has-text("Create Watchlist")',
  watchlistTable: 'table[aria-label="Sanctions screening watchlist rules"], table',
  watchlistTableRow: "table tbody tr",
  viewDetailsButton: 'button:has-text("View Details")',
  editConfigurationButton: 'button:has-text("Edit Configuration")',
  disableButton: 'button:has-text("Disable")',
  enableButton: 'button:has-text("Enable")',
  emptyState: "text=/no watchlist|no records|no data/i",
  validationMessage: '[role="alert"], .text-destructive, text=/required|mandatory|invalid/i',
  wizardDialog: '[role="dialog"].ssc-detail-panel-box, [role="dialog"]',
  wizardStepsNav: 'nav[aria-label="Wizard steps"]',
  wizardRuleInformation: 'h3:has-text("Rule Information"), text=/Rule Information/i',
  watchlistNameInput: 'input[placeholder*="Onboarding Sanctions"], [aria-label*="Watchlist Name"]',
  paginationNext: 'button[aria-label="Next page"], button:has-text("Next page")',
  paginationPrev: 'button[aria-label="Previous page"], button:has-text("Previous page")',
  fieldMappingPanel: 'nav[aria-label="Wizard steps"] >> text=Field Mapping, h3:has-text("Field Mapping"), text=/Field Mapping/i',
  listSelectionPanel: 'nav[aria-label="Wizard steps"] >> text=List Selection, h3:has-text("List Selection"), text=/List Selection/i',
  matchScorePanel: 'nav[aria-label="Wizard steps"] >> text=Match Score, h3:has-text("Match Score"), text=/Match Score Configuration/i',
  uploadPanel: "text=/upload|custom list/i",
  successMessage: "text=/saved successfully|configuration created|configuration updated/i",
};

export default ScreeningConfigurationLocators;
