import type { SmrExcelRow } from "./types";

function escapeStr(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
}

function pushUnique(steps: string[], step: string): void {
  if (step && !steps.includes(step)) {
    steps.push(step);
  }
}

export function parseNumberedSteps(testSteps: string): string[] {
  if (!testSteps.trim()) {
    return [];
  }
  const normalized = testSteps.replace(/(\d+)\.(?=[A-Za-z])/g, "$1. ");
  const parts = normalized.split(/\s*(?=\d+\.\s)/).map((p) => p.replace(/^\d+\.\s*/, "").trim()).filter(Boolean);
  if (parts.length > 0) {
    return parts;
  }
  return testSteps.split(/\.\s+/).map((p) => p.trim()).filter(Boolean);
}

function stepMatches(step: string, ...patterns: string[]): boolean {
  const s = step.toLowerCase();
  return patterns.some((p) => s.includes(p.toLowerCase()));
}

function rowBlob(row: SmrExcelRow): string {
  return `${row.subModule} ${row.taskDescription} ${row.testSteps} ${row.acceptanceCriteria} ${row.expectedResult} ${row.testData} ${row.preconditions}`.toLowerCase();
}

function featureGroup(subModule: string): string {
  return subModule.trim() || "Core";
}

const REPORT_DETAIL_SUBMODULES = [
  "comprehensive sanctions",
  "enhanced due diligence",
  "screening exception authorization",
  "screening logic governance",
  "exception list governance",
  "geographic risk exposure",
  "related party high-risk",
];

function isLandingPageRow(row: SmrExcelRow): boolean {
  const sub = row.subModule.toLowerCase().trim();
  const desc = row.taskDescription.toLowerCase();
  const exactLandingSubs = [
    "sanction mis reports",
    "dashboard counters",
    "report grid sorting",
    "search & filters",
    "search",
    "search security",
    "add report configuration",
    "date validation",
    "aml governance & audit",
  ];
  if (exactLandingSubs.includes(sub)) {
    return true;
  }
  if (sub.includes("sanction mis reports configuration")) {
    return true;
  }
  return /landing page|search functionality|statistics section|breadcrumb|pagination|sorting|dashboard counter|add report screen|sql injection|special character|frequency filter|status filter|clear search|report listing|report grid sorting/.test(desc);
}

function isLandingFilterScenario(row: SmrExcelRow): boolean {
  const blob = rowBlob(row);
  return (isLandingPageRow(row) || /search & filters|search and filters|dashboard counters|report grid sorting/i.test(row.subModule.toLowerCase()))
    && /status filter|frequency filter|filter updates report listing|multiple filters|clear search|clear filter|search criteria|landing page filter|report listing based on selected/i.test(blob);
}

function isKpiOrSummaryScenario(row: SmrExcelRow): boolean {
  const blob = rowBlob(row);
  return /kpi card|summary card|summary metrics|statistics section|dashboard counter|total hits|confirmed hits|nationality distribution|governance summary|exception summary/i.test(blob);
}

function isMetadataSectionScenario(row: SmrExcelRow): boolean {
  const blob = rowBlob(row);
  return /metadata section|generated date|generated by|total records information|report period loads|report metadata/i.test(blob)
    && !isConfigurationRow(row)
    && !isNegativeDateValidationRow(row);
}

function isReportDetailSubmodule(row: SmrExcelRow): boolean {
  const sub = row.subModule.toLowerCase();
  return REPORT_DETAIL_SUBMODULES.some((name) => sub.includes(name));
}

function isReportDetailSubmoduleOnly(row: SmrExcelRow): boolean {
  return isReportDetailSubmodule(row) && !isLandingFilterScenario(row) && !isLandingPageRow(row);
}

function needsReportDetailSetup(row: SmrExcelRow): boolean {
  if (isLandingFilterScenario(row)) {
    return false;
  }
  const desc = row.taskDescription.toLowerCase();
  const steps = row.testSteps.toLowerCase();
  const blob = `${desc} ${steps}`;
  if (/open report|view report|report detail|from report listing|report period|exception records|governance summary|logic change|export option|pdf export|excel export|metadata section|summary section|header information|generated date|generated by|total records|report page displays|click export|apply report filters|review export options|review metadata|review summary metrics|review exception records|review logic change|review governance records/i.test(blob)) {
    return true;
  }
  if (isLandingPageRow(row)) {
    return false;
  }
  if (isReportDetailSubmoduleOnly(row)) {
    return true;
  }
  const sub = row.subModule.toLowerCase();
  if (sub.includes("date range picker")) {
    return true;
  }
  return false;
}

function isConfigurationRow(row: SmrExcelRow): boolean {
  return row.subModule.toLowerCase().includes("configuration");
}

function shouldOpenAddReportDialogInSetup(row: SmrExcelRow): boolean {
  if (isConfigurationRow(row)) {
    return true;
  }
  if (needsReportDetailSetup(row) && !row.subModule.toLowerCase().includes("date validation")) {
    return false;
  }
  return row.subModule.toLowerCase().includes("date validation") || isNegativeDateValidationRow(row) || isPositiveDateValidationRow(row);
}

function isStatisticsRow(row: SmrExcelRow): boolean {
  if (needsReportDetailSetup(row)) {
    return false;
  }
  return /statistics section|summary cards|dashboard counter|total reports counter|generated counter|pending counter|daily\/weekly\/monthly counters/.test(rowBlob(row));
}

function isStatusColumnScenario(row: SmrExcelRow): boolean {
  const blob = rowBlob(row);
  return /status column|report status|status filter|status value|status dropdown|generated status|pending status/.test(blob)
    && !isStatisticsRow(row);
}

function inferReportName(row: SmrExcelRow): string {
  const blob = rowBlob(row);
  const reports = [
    "Comprehensive Sanctions Screening Intelligence Report",
    "Enhanced Due Diligence: PEP & Adverse Media Analytics Report",
    "Screening Exception Authorization & Tracking Report",
    "Geographic Risk Exposure Intelligence Report",
    "Related Party High-Risk Country Linkage Report",
    "Screening Logic Governance & Change Control Report",
    "Exception List Governance & Accountability Report",
  ];
  for (const name of reports) {
    if (blob.includes(name.toLowerCase())) {
      return name;
    }
  }
  if (/comprehensive sanctions/.test(blob)) {
    return "Comprehensive Sanctions Screening Intelligence Report";
  }
  if (/pep|adverse media/.test(blob)) {
    return "Enhanced Due Diligence: PEP & Adverse Media Analytics Report";
  }
  if (/exception authorization/.test(blob)) {
    return "Screening Exception Authorization & Tracking Report";
  }
  if (/logic governance/.test(blob)) {
    return "Screening Logic Governance & Change Control Report";
  }
  if (/exception list governance/.test(blob)) {
    return "Exception List Governance & Accountability Report";
  }
  if (/geographic risk/.test(blob)) {
    return "Geographic Risk Exposure Intelligence Report";
  }
  if (/related party/.test(blob)) {
    return "Related Party High-Risk Country Linkage Report";
  }
  return "Comprehensive Sanctions Screening Intelligence Report";
}

function inferSearchKeyword(row: SmrExcelRow, step: string): string {
  const blob = `${rowBlob(row)} ${step.toLowerCase()}`;
  if (/non-existing|no match|no matching|invalid search|zzzz/.test(blob)) {
    return "zzzz-no-match";
  }
  if (/sql injection/.test(blob)) {
    return "' OR 1=1 --";
  }
  if (/special character/.test(blob)) {
    return "@#$%";
  }
  if (/report id|mis-sanc/.test(blob)) {
    return "MIS-SANC-001";
  }
  if (/partial keyword|partial/.test(blob)) {
    return "Enhanced";
  }
  if (/report name/.test(blob)) {
    return "Comprehensive";
  }
  return "Comprehensive";
}

function isAuthDeniedScenario(row: SmrExcelRow): boolean {
  const blob = rowBlob(row);
  return /unauthorized|access denied|without permission|not authorized|restricted role/.test(blob)
    && !/authorized user/.test(blob);
}

function isPositiveDateValidationRow(row: SmrExcelRow): boolean {
  if (isKpiOrSummaryScenario(row) || isMetadataSectionScenario(row)) {
    return false;
  }
  const blob = rowBlob(row);
  return /same-day|same day|leap year|valid date range|handles same-day|accepts leap year|without errors|no errors/i.test(blob)
    && !/invalid date|date error|future date|must not|should not|reject/i.test(row.expectedResult.toLowerCase())
    && (row.subModule.toLowerCase().includes("date validation") || /date range|date picker|from date|to date/i.test(blob));
}

function isNegativeDateValidationRow(row: SmrExcelRow): boolean {
  const blob = rowBlob(row);
  return /invalid date|date error|future date|must not|should not|reject|invalid manually entered/i.test(blob);
}

function isEmptySearchRow(row: SmrExcelRow): boolean {
  return /no matching records|no matching report|non-existing keyword|non-existing search|returns no matching/i.test(rowBlob(row));
}

function isApiFailureRow(row: SmrExcelRow): boolean {
  return /api failure|network error|timeout|service unavailable|report failure|export failure/.test(rowBlob(row));
}

const OPEN = "await smrPage.openMisReportsDirect(testData.baseUrl)";

export function buildExcelSetupActions(row: SmrExcelRow): string[] {
  const steps: string[] = [];
  const blob = rowBlob(row);

  if (isApiFailureRow(row)) {
    pushUnique(steps, "await smrPage.mockMisReportApiFailure()");
  }

  if (isAuthDeniedScenario(row)) {
    pushUnique(steps, "await smrPage.mockUnauthorized()");
  }

  if (stepMatches(blob, "sidebar", "navigation menu", "sanction screening") && !blob.includes("direct url")) {
    pushUnique(steps, OPEN);
    pushUnique(steps, "await smrPage.openMisReportsFromSidebar()");
  } else {
    pushUnique(steps, OPEN);
  }

  if (!needsReportDetailSetup(row)) {
    pushUnique(steps, "await smrPage.expectMisReportsPageLoaded()");
  }

  if (shouldOpenAddReportDialogInSetup(row)) {
    pushUnique(steps, "await smrPage.clickAddNewRule()");
  } else if (isEmptySearchRow(row)) {
    pushUnique(steps, "await smrPage.ensureLandingFiltersVisible()");
  }

  if (needsReportDetailSetup(row)) {
    const reportName = inferReportName(row);
    pushUnique(steps, `await smrPage.openReportView('${escapeStr(reportName)}')`);
  }

  return steps;
}

export function buildExcelStepActions(row: SmrExcelRow): string[] {
  const steps: string[] = [];
  const numbered = parseNumberedSteps(row.testSteps);
  const blob = rowBlob(row);
  const reportName = inferReportName(row);

  for (const s of numbered) {
    if (stepMatches(s, "login", "log in", "logged in")) {
      continue;
    }
    if (stepMatches(s, "navigate to sanction", "sanction screening module", "sanctions screening")) {
      pushUnique(steps, "await smrPage.openMisReportsFromSidebar()");
      continue;
    }
    if (stepMatches(s, "click sanction mis", "screening mis reports", "mis reports menu")) {
      pushUnique(steps, "await smrPage.openMisReportsFromSidebar()");
      continue;
    }
    if (stepMatches(s, "direct url", "enter url", "open direct")) {
      pushUnique(steps, OPEN);
      pushUnique(steps, "await smrPage.expectMisReportsPageLoaded()");
      continue;
    }
    if (stepMatches(s, "review statistics section", "review all statistics cards")) {
      pushUnique(steps, "await smrPage.expectStatisticsCardsVisible()");
    } else if (stepMatches(s, "review header section", "review page header")) {
      pushUnique(steps, needsReportDetailSetup(row)
        ? "await smrPage.expectReportDetailHeaderVisible()"
        : "await smrPage.expectPageHeaderVisible()");
    } else if (stepMatches(s, "review metadata section", "report period")) {
      pushUnique(steps, "await smrPage.expectReportPeriodVisible()");
    } else if (stepMatches(s, "review summary section", "review summary metrics", "governance summary")) {
      pushUnique(steps, "await smrPage.expectReportSummarySectionVisible()");
    } else if (stepMatches(s, "review exception records", "exception records section", "logic change records", "governance records", "records section")) {
      pushUnique(steps, "await smrPage.expectReportDataDisplayed()");
    } else if (stepMatches(s, "enter report name", "enter partial keyword", "enter non-existing keyword", "enter search", "type in search", "enter keyword")) {
      pushUnique(steps, `await smrPage.searchReports('${escapeStr(inferSearchKeyword(row, s))}')`);
    } else if (stepMatches(s, "enter report id", "search reports field")) {
      pushUnique(steps, `await smrPage.searchReports('${escapeStr(inferSearchKeyword(row, s))}')`);
    } else if (stepMatches(s, "count grid records", "count generated", "count pending", "count frequency", "compare with")) {
      pushUnique(steps, "await smrPage.expectDashboardCountersMatchGrid()");
    } else if (stepMatches(s, "click filter", "open filter", "locate frequency filter", "locate status filter")) {
      pushUnique(steps, "await smrPage.clickFilterButton()");
    } else if (/select a frequency|select frequency option|select frequency/i.test(s)) {
      pushUnique(steps, "await smrPage.clickFilterButton()");
      const value = /weekly/i.test(s + blob) ? "Weekly" : /monthly/i.test(s + blob) ? "Monthly" : "Daily";
      pushUnique(steps, `await smrPage.selectLandingFilter('Frequency', '${value}')`);
    } else if (/select status option|select a status|select status/i.test(s)) {
      pushUnique(steps, "await smrPage.clickFilterButton()");
      const value = /pending/i.test(s + blob) ? "Pending" : "Generated";
      pushUnique(steps, `await smrPage.selectLandingFilter('Status', '${value}')`);
    } else if (stepMatches(s, "select frequency", "frequency filter", "choose frequency")) {
      const value = /daily/i.test(s + blob) ? "Daily" : /weekly/i.test(s + blob) ? "Weekly" : /monthly/i.test(s + blob) ? "Monthly" : "Daily";
      pushUnique(steps, `await smrPage.selectLandingFilter('Frequency', '${value}')`);
    } else if (stepMatches(s, "select status", "status filter", "choose status")) {
      const value = /pending/i.test(s + blob) ? "Pending" : /generated/i.test(s + blob) ? "Generated" : "Generated";
      pushUnique(steps, `await smrPage.selectLandingFilter('Status', '${value}')`);
    } else if (stepMatches(s, "apply filter", "apply filters", "apply available filters")) {
      pushUnique(steps, "await smrPage.clickApplyFilters()");
    } else if (stepMatches(s, "clear filter", "clear search", "reset filter")) {
      pushUnique(steps, "await smrPage.clearLandingFilters()");
    } else if (stepMatches(s, "add new rule", "add report", "create rule", "click add report", "configure report")) {
      if (!isConfigurationRow(row) || stepMatches(s, "click add report", "add report")) {
        pushUnique(steps, "await smrPage.clickAddNewRule()");
      }
    } else if (/^view report\b|click view\b/i.test(s.trim())) {
      pushUnique(steps, `await smrPage.clickViewForReport('${escapeStr(reportName)}')`);
    } else if (/^open report\b/i.test(s.trim())) {
      pushUnique(steps, `await smrPage.openReportView('${escapeStr(reportName)}')`);
    } else if (/^click export pdf\b|^export pdf\b/i.test(s.trim())) {
      pushUnique(steps, `await smrPage.clickExportReport('PDF')`);
    } else if (/^click export excel\b|^export excel\b/i.test(s.trim())) {
      pushUnique(steps, `await smrPage.clickExportReport('Excel')`);
    } else if (/^review report grid\b|^review grid\b/i.test(s.trim())) {
      pushUnique(steps, "await smrPage.expectReportsTableVisible()");
    } else if (stepMatches(s, "search")) {
      pushUnique(steps, `await smrPage.searchReports('${escapeStr(inferSearchKeyword(row, s))}')`);
    } else if (stepMatches(s, "generate", "click generate", "run report", "generate report")) {
      pushUnique(steps, `await smrPage.clickGenerateForReport('${escapeStr(reportName)}')`);
    } else if (/enter invalid date|invalid date manually|type invalid date/i.test(s)) {
      pushUnique(steps, "await smrPage.openDateRangePicker()");
      pushUnique(steps, "await smrPage.enterInvalidDate()");
    } else if (stepMatches(s, "click date range", "date range field", "select date", "from date", "to date", "pick date")) {
      if (isConfigurationRow(row) || row.subModule.toLowerCase().includes("date validation")) {
        pushUnique(steps, "await smrPage.clickAddNewRule()");
      }
      pushUnique(steps, "await smrPage.openDateRangePicker()");
      if (stepMatches(s, "apply", "select", "pick") || isPositiveDateValidationRow(row)) {
        pushUnique(steps, "await smrPage.selectDefaultDateRange()");
      }
    } else if (stepMatches(s, "export", "download")) {
      const format = stepMatches(s, "csv") ? "CSV" : stepMatches(s, "pdf") ? "PDF" : "Excel";
      pushUnique(steps, `await smrPage.clickExportReport('${format}')`);
    } else if (stepMatches(s, "sort", "column header")) {
      const col = /report name/i.test(s) ? "Report Name" : /frequency/i.test(s) ? "Frequency" : /status/i.test(s) ? "Status" : "Report ID";
      pushUnique(steps, `await smrPage.sortReportColumn('${col}')`);
    } else if (stepMatches(s, "pagination", "next page", "previous page", "items per page")) {
      if (stepMatches(s, "next")) {
        pushUnique(steps, "await smrPage.goToNextPage()");
      } else if (stepMatches(s, "previous")) {
        pushUnique(steps, "await smrPage.goToPreviousPage()");
      } else {
        pushUnique(steps, "await smrPage.expectPaginationVisible()");
      }
    } else if (stepMatches(s, "refresh", "reload")) {
      pushUnique(steps, "await smrPage.refreshPage()");
    } else if (stepMatches(s, "logout", "log out", "session")) {
      pushUnique(steps, "await smrPage.performLogoutAndReturn()");
    } else if (stepMatches(s, "save", "submit", "confirm")) {
      pushUnique(steps, "await smrPage.clickConfirmAction()");
    } else if (stepMatches(s, "cancel", "close")) {
      pushUnique(steps, "await smrPage.closeActiveDialog()");
    } else if (
      stepMatches(s, "inspect", "observe", "verify", "validate", "check")
      || (/^review\b/i.test(s.trim()) && !/^review (report grid|grid|metadata|summary|exception|export|header|statistics|logic|governance|records)/i.test(s.trim()))
    ) {
      // assertions handle expected results
    } else {
      pushUnique(steps, `// TODO: Excel step not mapped — "${escapeStr(s)}"`);
    }
  }

  return steps;
}

export function buildExcelAssertionActions(row: SmrExcelRow): string[] {
  const steps: string[] = [];
  const blob = rowBlob(row);
  const onDetail = needsReportDetailSetup(row);

  if (/unauthorized|access denied|cannot access|not authorized|denied/.test(blob)) {
    pushUnique(steps, "await smrPage.expectAccessDenied()");
  }
  if (/landing page|page should open|module.*open|without errors|mis reports page/.test(blob)) {
    pushUnique(steps, "await smrPage.expectMisReportsPageLoaded()");
  }
  if (/breadcrumb/.test(blob)) {
    pushUnique(steps, "await smrPage.expectBreadcrumbVisible()");
  }
  if (/page title|header|subtitle/.test(blob) && !onDetail) {
    pushUnique(steps, "await smrPage.expectPageHeaderVisible()");
  }
  if (/report header|header information/.test(blob) && onDetail) {
    pushUnique(steps, "await smrPage.expectReportDetailHeaderVisible()");
  }
  if (isKpiOrSummaryScenario(row)) {
    pushUnique(steps, "await smrPage.expectReportSummarySectionVisible()");
  }
  if (isMetadataSectionScenario(row) && onDetail) {
    pushUnique(steps, "await smrPage.expectReportPeriodVisible()");
    pushUnique(steps, "await smrPage.expectReportDetailHeaderVisible()");
  } else if (/report period|reporting period|metadata section/.test(blob) && onDetail) {
    pushUnique(steps, "await smrPage.expectReportPeriodVisible()");
  }
  if (/summary section|summary metrics|governance summary|exception summary/.test(blob)) {
    pushUnique(steps, "await smrPage.expectReportSummarySectionVisible()");
  }
  if (/report grid|reports table|report list|matching report|report id|report name|frequency column|status column/.test(blob) && !isConfigurationRow(row)) {
    pushUnique(steps, "await smrPage.expectReportsTableVisible()");
  }
  if (isStatisticsRow(row)) {
    pushUnique(steps, "await smrPage.expectStatisticsCardsVisible()");
    if (/counter matches|reconcile|compare/.test(blob)) {
      pushUnique(steps, "await smrPage.expectDashboardCountersMatchGrid()");
    }
  }
  if (/filter|search|report filters/.test(blob) && !/clear filter|filters reset|fields cleared|no matching/.test(blob)) {
    if (isLandingFilterScenario(row) || (!onDetail && !row.subModule.toLowerCase().includes("date range picker"))) {
      pushUnique(steps, "await smrPage.expectFilterControlsVisible()");
    } else if (row.subModule.toLowerCase().includes("date range picker") || onDetail) {
      pushUnique(steps, "await smrPage.expectReportDetailFiltersVisible()");
    } else {
      pushUnique(steps, "await smrPage.expectFilterControlsVisible()");
    }
  }
  if (/clear filter|filters reset|fields cleared|restores complete report listing/.test(blob)) {
    pushUnique(steps, "await smrPage.expectFiltersCleared()");
  }
  if (/no matching|no records|empty/.test(blob) && /search/.test(blob)) {
    pushUnique(steps, "await smrPage.expectEmptySearchResults()");
  }
  if (/report period|reporting period|generated date|metadata section/.test(blob) && onDetail) {
    pushUnique(steps, "await smrPage.expectReportPeriodVisible()");
  }
  if (/generate.*disabled|button.*disabled|cannot generate/.test(blob)) {
    pushUnique(steps, "await smrPage.expectGenerateActionState('disabled')");
  }
  if (/generate.*enabled|report generation.*start|generated successfully/.test(blob)) {
    pushUnique(steps, "await smrPage.expectGenerateActionState('enabled')");
  }
  if (isStatusColumnScenario(row)) {
    pushUnique(steps, "await smrPage.expectReportStatusVisible()");
  }
  if (isConfigurationRow(row) && /configuration|add new rule|add report|report id field|from date|to date|status dropdown|report name field|frequency field|all configured fields/.test(blob)) {
    pushUnique(steps, "await smrPage.expectReportConfigurationPanelVisible()");
  }
  if (isConfigurationRow(row) && /report id field|auto-generated|report id is/.test(blob)) {
    pushUnique(steps, "await smrPage.expectAddReportFieldVisible('Report ID')");
  }
  if (isConfigurationRow(row) && /from date|to date/.test(blob)) {
    pushUnique(steps, "await smrPage.expectAddReportFieldVisible('From Date')");
    pushUnique(steps, "await smrPage.expectAddReportFieldVisible('To Date')");
  }
  if (isConfigurationRow(row) && /status dropdown|status value|configured values/.test(blob)) {
    pushUnique(steps, "await smrPage.expectAddReportFieldVisible('Status')");
  }
  if (/date range|date picker|calendar|from date|to date/.test(blob) && !/date validation|invalid date|add report|configuration/.test(blob)) {
    pushUnique(steps, "await smrPage.expectDateRangePickerVisible()");
  }
  if (isPositiveDateValidationRow(row)) {
    pushUnique(steps, "await smrPage.expectDateRangeAccepted()");
  } else if (isNegativeDateValidationRow(row) && !isKpiOrSummaryScenario(row)) {
    pushUnique(steps, "await smrPage.expectDateValidationFeedback()");
  } else if (/date validation|invalid date|future date|date error|leap year|same-day/.test(blob) && !isKpiOrSummaryScenario(row) && !/without errors|no errors|acceptance|loads successfully|metadata section|kpi card|summary card/i.test(blob)) {
    pushUnique(steps, "await smrPage.expectDateValidationFeedback()");
  }
  if (/export|download/.test(blob) && !/failure|error/.test(blob)) {
    pushUnique(steps, "await smrPage.expectExportActionAvailable()");
  }
  if (/export failure|download fail|export error/.test(blob)) {
    pushUnique(steps, "await smrPage.expectExportFailureHandled()");
  }
  if (/sort|ascending|descending|column order/.test(blob)) {
    pushUnique(steps, "await smrPage.expectReportColumnSorted()");
  }
  if (/pagination|page navigation|items per page/.test(blob)) {
    pushUnique(steps, "await smrPage.expectPaginationVisible()");
  }
  if (/empty state|no reports|no data/.test(blob) && !/search/.test(blob)) {
    pushUnique(steps, "await smrPage.expectEmptyStateVisible()");
  }
  if (/risk score|score validation|threshold/.test(blob) && !isConfigurationRow(row)) {
    pushUnique(steps, "await smrPage.expectRiskScoreValidation()");
  }
  if (/data accuracy|report data|grid data|record accuracy|exception records|logic change|maker information|checker information|accountability|validity information/.test(blob)) {
    pushUnique(steps, "await smrPage.expectReportDataDisplayed()");
  }
  if (/api failure|network error|timeout|graceful|error message/.test(blob) && isApiFailureRow(row)) {
    pushUnique(steps, "await smrPage.expectApiFailureHandledGracefully()");
  }
  if (/layout|alignment|responsive|ui integrity/.test(blob)) {
    pushUnique(steps, "await smrPage.expectLayoutStable()");
  }
  if (/audit logging|user and timestamp|governance & audit/.test(blob)) {
    pushUnique(steps, "await smrPage.expectAuditTrailIndicators()");
  }
  if (steps.length === 0) {
    pushUnique(steps, onDetail
      ? "await smrPage.expectReportDetailShellLoaded()"
      : "await smrPage.expectPageShellLoaded()");
  }

  return steps;
}

export function buildExcelAlignedLogic(row: SmrExcelRow): string {
  const lines: string[] = [];
  for (const block of [
    buildExcelSetupActions(row),
    buildExcelStepActions(row),
    buildExcelAssertionActions(row),
  ]) {
    for (const step of block) {
      pushUnique(lines, step);
    }
  }
  return lines.join(";\n    ");
}

export function formatTestTitle(row: SmrExcelRow): string {
  const feature = featureGroup(row.subModule);
  const action = row.taskDescription.replace(/^Verify\s+/i, "").trim();
  return `Case ID:${row.id} - ${feature} → ${action}`;
}

export function formatExcelComment(row: SmrExcelRow): string {
  return `// Excel Test Case ID: ${row.id}\n  // Excel Scenario: ${row.taskDescription}`;
}
