const Customer360Locators = {
  customer360Title: "h1.customer-360-title, h1:has-text('Customer 360'), [class*='customer-360'] h1",
  customer360Subtitle: ".customer-360-subtitle, [class*='subtitle']",
  customer360Link: "a.sidebar-link[href='/kyc/customer-360'], a:has-text('Customer 360° View')",
  customerSearchInput: "input.lookup-search-input, input[placeholder*='Search customer'], input[placeholder*='Search by'], input[type='search']",
  customerSearchButton: "button:has-text('Search'), button[aria-label*='Search']",
  customerSearchResults: ".lookup-result-card, .lookup-recent-card, [class*='search-result'], .customer-search-results, table tbody tr",
  headerStrip: ".cust-header, [class*='header-strip'], [class*='customer-header'], .customer-360-header",
  customerName: ".cust-name, [class*='customer-name'], [data-testid='customer-name']",
  customerIdentifier: ".cust-meta, [class*='customer-id'], [class*='cif-id'], [data-testid='customer-id']",
  pepBadge: "[class*='pep-badge'], .pep-badge",
  adverseMediaBadge: "[class*='adverse-media'], .adverse-media-badge",
  riskScoreBadge: "[class*='risk-score'], [class*='risk-badge'], [data-testid='risk-score']",
  alertCountBadge: "[class*='alert-count'], [class*='badge']:has-text('Alert')",
  strSarIndicator: "[class*='str-badge'], [class*='sar-badge'], .str-badge, .sar-badge",
  customerTypeToggle: "[class*='customer-type-toggle'], [role='tablist']:has-text('Individual')",
  individualToggle: "button:has-text('Individual'), [role='tab']:has-text('Individual')",
  corporateToggle: "button:has-text('Corporate'), [role='tab']:has-text('Corporate')",
  tabList: ".tab-bar, [role='tablist'], .customer-360-tabs, nav[class*='tabs']",
  tabPanel: ".c360-tabpanel, .panel--tab-content, [role='tabpanel'], .tab-panel, [class*='tab-content']",
  overviewTab: "[role='tab']:has-text('Overview')",
  relationshipsTab: "[role='tab']:has-text('Relationships')",
  screeningTab: "[role='tab']:has-text('Screening')",
  riskTab: "[role='tab']:has-text('Risk')",
  kycCddTab: "[role='tab']:has-text('KYC'), [role='tab']:has-text('CDD')",
  accountsTab: "[role='tab']:has-text('Accounts')",
  transactionsTab: "[role='tab']:has-text('Transactions')",
  alertsTab: "[role='tab']:has-text('Alerts')",
  regulatoryReportsTab: "[role='tab']:has-text('Regulatory')",
  kycGapReportTab: "[role='tab']:has-text('KYC Gap Report')",
  auditTab: "[role='tab']:has-text('Audit')",
  kpiCard: ".ov-tile, .kpi-card, [class*='kpi-card'], [class*='kpi']",
  riskDonutChart: ".risk-wheel, [class*='donut'], [class*='risk-chart'], canvas, svg[class*='chart']",
  keyRelationshipsWidget: "[class*='relationships-widget'], [class*='key-relationships']",
  screeningSummaryWidget: "[class*='screening-summary']",
  transactionMetricsWidget: "[class*='transaction-metrics'], [class*='transaction-summary']",
  tabTable: "table, [role='grid'], [class*='data-table']",
  tabTableRow: "table tbody tr, [role='row']",
  expandCardButton: "button[aria-label*='Expand'], button:has-text('Expand'), [class*='expand']",
  collapseCardButton: "button[aria-label*='Collapse'], button:has-text('Collapse'), [class*='collapse']",
  exportButton: "button:has-text('Export')",
  retryButton: "button:has-text('Retry'), button:has-text('Try Again')",
  loadingIndicator: "[class*='loading'], [class*='skeleton'], [class*='spinner'], [aria-busy='true']",
  emptyState: ".lookup-empty-card, .lookup-not-found, .empty-state, [class*='empty-state'], [class*='no-data']",
  paginationNext: "button[aria-label='Next page'], button:has-text('Next')",
  filterInput: "input[placeholder*='Filter'], input[placeholder*='Search']",
  maskedField: "[class*='masked'], [data-masked='true'], [class*='pii-mask']",
};

export default Customer360Locators;
