const IgnoreWordsConfigurationLocators = {
  pageTitle: "h1:has-text('Ignore Words'), h1:has-text('Ignore Word Configuration'), h1:has-text('Screening'), [class*='ignore-words'] h1",
  pageSubtitle: ".ignore-words-subtitle, [class*='subtitle']",
  configurationMenu: "button:has-text('Configuration'), button:has-text('Configurations'), [aria-label*='Configuration']",
  configurationSubmenu: "[class*='configuration-submenu'], nav:has-text('Configuration')",
  ignoreWordsLink: "a:has-text('Ignore Words'), a:has-text('Ignore Word Configuration'), a[href*='ignore-words'], a[href*='screening-ignore-words']",
  toolbar: "[class*='toolbar'], [class*='action-bar'], header[class*='toolbar']",
  searchInput: "input[placeholder*='Search ignore'], input[placeholder*='ignore word'], input[placeholder*='phrase'], input[placeholder*='Search'], input[type='search']",
  searchClearButton: "button[aria-label*='Clear'], button:has-text('Clear')",
  tabList: "[role='tablist'], .ignore-words-tabs, nav[class*='tabs']",
  tabPanel: "[role='tabpanel'], .tab-panel, [class*='tab-content']",
  activeTab: "[role='tab'][aria-selected='true']",
  dataTable: "table, [role='grid'], [class*='data-table'], [class*='ignore-words-table']",
  tableHeader: "table thead th, [role='columnheader']",
  tableRow: "table tbody tr, [role='row']",
  categoryBadge: "[class*='category-badge'], [class*='badge'][class*='category'], span[class*='pill']",
  statusBadge: "[class*='status-badge'], [data-testid='status-badge']",
  riskLevelBadge: "[class*='risk-level'], [class*='risk-badge'], [data-testid='risk-level-badge']",
  matchTypeBadge: "[class*='match-type'], [class*='match-badge'], [data-testid='match-type-badge']",
  rowActionButton: "button[aria-label*='action'], button:has-text('Disable'), button:has-text('Enable'), [class*='row-action']",
  rowActionsMenu: "button[aria-label*='More'], button[aria-label*='Actions'], [class*='kebab']",
  exportButton: "button:has-text('Export')",
  addCategoryButton: "button:has-text('Add Category')",
  categoryControlsButton: "button:has-text('Category Controls'), button[aria-label*='Category Controls']",
  addIgnoreWordButton: "button:has-text('Add Ignore Word'), button:has-text('New Ignore Word')",
  bulkUploadButton: "button:has-text('Bulk Upload'), button:has-text('Import'), button:has-text('Upload')",
  liveNarrativeTester: "[class*='narrative-tester'], [class*='live-narrative'], [data-testid='narrative-tester']",
  makerCheckerQueue: "[class*='maker-checker'], [class*='approval-queue'], button:has-text('Approval Queue')",
  addCategoryModal: "#modal-add-category, [role='dialog'][aria-label='Add Category'], [class*='add-category-modal']:not(.iwc-hidden)",
  categoryControlsModal: "#modal-category-controls, [role='dialog'][aria-label='Category Controls'], [class*='category-controls']:not(.iwc-hidden)",
  addIgnoreWordPanel: "#modal-add-ignore-word, aside.add-ignore-word[aria-label='Add Ignore Word'], [role='dialog'][aria-label='Add Ignore Word']",
  bulkUploadModal: "#modal-bulk-upload, [role='dialog'][aria-label='Bulk Upload'], [class*='bulk-upload']:not(.iwc-hidden)",
  checkerApprovalModal: "#modal-checker-approval, [role='dialog'][aria-label='Checker Approval'], [class*='checker-approval']:not(.iwc-hidden)",
  wordHistoryPanel: "#modal-word-history, [class*='word-history']:not(.iwc-hidden), aside[aria-label='Word History']",
  categoryNameInput: "input[name*='category'], input[placeholder*='Category name'], [data-testid='category-name']",
  categoryDescriptionInput: "textarea[name*='description'], input[placeholder*='Description'], [data-testid='category-description']",
  ignoreWordPhraseInput: "input[name*='ignore'], input[placeholder*='ignore word'], textarea[placeholder*='ignore word'], textarea[placeholder*='phrase']",
  categorySelect: "select[name*='category'], [data-testid='category-select']",
  riskLevelSelect: "select[name*='risk'], [data-testid='risk-level-select'], [class*='risk-level-select']",
  matchTypeSelect: "select[name*='match'], [data-testid='match-type-select'], [class*='match-type-select']",
  categoryFilter: "select[name*='filter'], [data-testid='category-filter'], [class*='category-filter']",
  narrativeTextarea: "textarea[placeholder*='narrative'], textarea[name*='narrative'], [data-testid='narrative-input']",
  checkerCommentInput: "textarea[name*='comment'], input[placeholder*='comment'], input[placeholder*='reason'], [data-testid='approval-comment']",
  modalOverlay: "[class*='overlay'], [class*='backdrop']",
  panelOverlay: "[class*='panel-overlay'], [class*='drawer-overlay'], [class*='overlay'][class*='panel']",
  backArrow: "button[aria-label*='Back'], button[class*='back'], [class*='back-arrow']",
  breadcrumbNav: "nav[aria-label*='breadcrumb'], [class*='breadcrumb']",
  topBar: "[class*='top-bar'], header[class*='app-header'], [data-testid='top-bar']",
  statusBar: "[class*='status-bar'], footer[class*='status'], [data-testid='status-bar']",
  sidebar: "[class*='sidebar'], nav[class*='sidebar'], aside[class*='sidebar']",
  sidebarActiveItem: "[class*='sidebar'] [aria-current='page'], [class*='sidebar'] [class*='active'], [class*='sidebar'] a[class*='selected']",
  mainContent: "main, [class*='main-content'], [class*='content-area']",
  modalSubmitButton: "button:has-text('Submit'), button:has-text('Save'), button:has-text('Create'), button:has-text('Add')",
  modalCancelButton: "button:has-text('Cancel'), button:has-text('Close')",
  modalApproveButton: "button:has-text('Approve'), button:has-text('Confirm')",
  modalRejectButton: "button:has-text('Reject'), button:has-text('Decline')",
  modalConfirmButton: "button:has-text('Confirm'), button:has-text('Yes'), button:has-text('Disable')",
  retryButton: "button:has-text('Retry'), button:has-text('Try Again')",
  loadingIndicator: "[class*='loading'], [class*='skeleton'], [class*='spinner'], [aria-busy='true']",
  emptyState: ".empty-state, [class*='empty-state'], [class*='no-data'], [class*='no-results']",
  errorState: "[class*='error-state'], [role='alert'], [class*='error-message']",
  validationError: "[class*='validation-error'], [class*='field-error'], .error-text",
  duplicateError: "[class*='duplicate'], text=/duplicate/i",
  toastNotification: "[class*='toast'], [role='status'][class*='toast'], .notification-toast",
  paginationNext: "button[aria-label='Next page'], button:has-text('Next')",
  bulkUploadFileInput: "input[type='file']",
  bulkUploadTemplateLink: "a:has-text('template'), button:has-text('Download template')",
  narrativeHighlight: "[class*='highlight'], mark, [class*='match-highlight']",
  historyTimeline: "[class*='timeline'], [class*='history-list'], [class*='audit-trail']",
  bulkUploadValidationResults: "[class*='validation-results'], [class*='upload-results'], [class*='import-summary']",
  configurationMenuSearch: "input[placeholder*='Search menu'], input[aria-label*='Search'], [class*='menu-search'] input",
};

export default IgnoreWordsConfigurationLocators;
